[package]
name = "vdb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.'*']
opt-level = 's'
debug = true

[dependencies]
byteorder = "1.4"
thiserror = "1"
glam = "0.23"
bitvec = "1"
half = { version = "2.2.1", features = ["bytemuck"] }
bitflags = "1"
bytemuck = { version ="1.13", features = ["extern_crate_alloc"] }
flate2 = "1"
blosc-src = "0.1.1"
log = "0.4"

[dev-dependencies]
bevy = "0.9"
bevy_flycam  = "0.9"
bevy-aabb-instancing = { git = "https://github.com/ForesightMiningSoftwareCorporation/bevy-aabb-instancing.git" }
smooth-bevy-cameras = { git = "https://github.com/olegomon/smooth-bevy-cameras" }