[package]
name = "vdb-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.'*']
opt-level = 's'
debug = true

[dependencies]
byteorder = "1.4"
thiserror = "1"
glam = "0.23"
bitvec = "1"
half = { version = "2.2.1", features = ["bytemuck"] }
bitflags = "1"
bytemuck = { version ="1.13", features = ["extern_crate_alloc"] }
flate2 = "1"